Repository automotiveMastermind/condo, pull requests merged in 2018-03, with the labels that each got.

#174 docs: update readme
  README.md
  appveyor.yml
  docs/concepts/frameworks.md
  docs/services/pet-store.swagger.json
  docs/services/toc.yml
Labels: review

#175 docs: lifecycle.md
  docs/concepts/lifecycle.md
Labels: review

#178 feat(clean): allow skip clean
  src/AM.Condo/Targets/Clean.targets
  src/AM.Condo/Targets/Lifecycle.targets
Labels: enhancement

#179 fix(scripts): skip install of dotnet v1 when host running ubuntu 16.10 or greater
  src/AM.Condo/Scripts/condo.sh
Labels: bug, review

#180 fix(dotnet): download and build on windows
  build/dependencies.props
  template/condo.ps1
Labels: review

#181 fix: msbuildversion should be buildversion in csproj
  src/AM.Condo/condo.csproj
  test/AM.Condo.Test/AM.Condo.Test.csproj
Labels: review
