Repository automotiveMastermind/condo, pull requests merged in 2018-09, with the labels that each got.

#221 fix(docker): vsts agent start script
  src/AM.Condo/Dockerfile.dotnet-1-docker-vsts-agent
  src/AM.Condo/Dockerfile.dotnet-1-vsts-agent
  src/AM.Condo/Dockerfile.dotnet-2-docker-vsts-agent
  src/AM.Condo/Dockerfile.dotnet-2-vsts-agent
Labels: review

#222 feat(docker): handle arbitrary workdir in docker build
  condo.sln
  src/AM.Condo/Diagnostics/ConsoleLogger.cs
  src/AM.Condo/Dockerfile.dotnet-1
  src/AM.Condo/Dockerfile.dotnet-1-docker-vsts-agent
  src/AM.Condo/Dockerfile.dotnet-1-docker.latest
  src/AM.Condo/Dockerfile.dotnet-1-vsts-agent
  src/AM.Condo/Dockerfile.dotnet-2
  src/AM.Condo/Dockerfile.dotnet-2-docker
  src/AM.Condo/Dockerfile.dotnet-2-docker-vsts-agent
  src/AM.Condo/Dockerfile.dotnet-2-vsts-agent
  src/AM.Condo/Program.cs
  src/AM.Condo/Scripts/condo.ps1
  src/AM.Condo/Scripts/condo.sh
  src/AM.Condo/Targets/Clean.targets
  src/AM.Condo/Tasks/GetProjectMetadata.cs
  src/AM.Condo/cli.sh
  src/AM.Condo/condo.csproj
  src/AM.Condo/condo.msbuild.rsp
  src/AM.Condo/condo.sh
  src/AM.Condo/docker.sh
  src/Directory.Build.props
Labels: enhancement, review

#223 build(azure): add azure pipeline and job spec
  .azure/cli.yaml
  .gitignore
  azure-pipeline.yaml
Labels: enhancement, review

#225 build(azure): move pool to pipelines
  .azure/cli.yaml
  .build/dependencies.props
  .circleci/config.yml
  .gitignore
  azure-pipelines.yaml
  src/AM.Condo/Targets/Version.targets
  src/AM.Condo/Tasks/SetDockerConfig.cs
  src/Directory.Build.props
  src/stylecop.ruleset
  template/condo.sh
  test/Directory.Build.props
Labels: review

#227 fix: restore build deps folder name
  build/dependencies.props
  src/Directory.Build.props
  template/condo.sh
  test/Directory.Build.props
Labels: bug, review

#226 docs(readme): fix maintenance urls
  README.md
Labels: review

#228 fix: change azure-pipeline to step template
  .azure/cli.yaml
  azure-pipelines.yaml
Labels: review
