Repository automotiveMastermind/condo, pull requests merged in 2018-06, with the labels that each got.

#199 feat(dotnet): upgrade to core 2.1
  global.json
  src/AM.Condo/Dockerfile.dotnet-1
  src/AM.Condo/Dockerfile.dotnet-1-docker
  src/AM.Condo/Dockerfile.dotnet-2
  src/AM.Condo/Dockerfile.dotnet-2-docker.latest
  src/AM.Condo/Scripts/condo.ps1
  src/AM.Condo/Scripts/condo.sh
  src/AM.Condo/condo.csproj
  test/AM.Condo.ChangeLog.Test/AM.Condo.ChangeLog.Test.csproj
  test/AM.Condo.E2E.Test/AM.Condo.E2E.Test.csproj
  test/AM.Condo.IO.Test/AM.Condo.IO.Test.csproj
  test/AM.Condo.MultipleTargets.Test/AM.Condo.MultipleTargets.Test.csproj
  test/AM.Condo.Test/AM.Condo.Test.csproj
Labels: review

#200 fix: continue to include 2.1.105 sdk for now
  src/AM.Condo/Scripts/condo.ps1
  src/AM.Condo/Scripts/condo.sh
Labels: bug, review

#202 fix: resolve behavior changes in the .net 2.1.300 sdk
  .docker/Dockerfile.test.debian-8
  .docker/Dockerfile.test.fedora-23
  .docker/Dockerfile.test.fedora-24
  .docker/Dockerfile.test.ubuntu-trusty
  .docker/Dockerfile.test.ubuntu-xenial
  .docker/docker-compose.ci.yml
  .docker/docker-compose.debug.yml
  .docker/docker-task.sh
  CHANGELOG.md
  build/dependencies.props
  src/AM.Condo/AM.Condo.tasks
  src/AM.Condo/NuGetMachineSettings.cs
  src/AM.Condo/Scripts/condo.ps1
  src/AM.Condo/Scripts/condo.sh
  src/AM.Condo/Targets/Compile/Dotnet.targets
  src/AM.Condo/Targets/Prepare/Dotnet.targets
  src/AM.Condo/Targets/Publish/Dotnet.targets
  src/AM.Condo/Targets/Version/Conventional.targets
  src/AM.Condo/Tasks/GetProjectMetadata.cs
  src/AM.Condo/Tasks/InstallNuGetPackage.cs
  src/AM.Condo/Tasks/PushNuGetPackage.cs
  test/AM.Condo.MultipleTargets.Test/AM.Condo.MultipleTargets.Test.csproj
  test/AM.Condo.Test/NuGetMocks.cs
  test/Directory.Build.props
Labels: enhancement, review

#198 fix(ubuntu): skip dotnet core 1.x install on distro's greater than 16.04
  src/AM.Condo/Scripts/condo.sh
Labels: review

#206 fix(docker): update images to dotnet core 2.1
  CHANGELOG.md
  docs/condo/docker-in-docker.md
  docs/condo/environment-variables.md
  src/AM.Condo/Dockerfile.dotnet-1
  src/AM.Condo/Dockerfile.dotnet-1-docker
  src/AM.Condo/Dockerfile.dotnet-2
  src/AM.Condo/Dockerfile.dotnet-2-docker.latest
  src/AM.Condo/Targets/Publish/Docker.targets
  src/AM.Condo/Tasks/GetDockerMetadata.cs
Labels: review

#208 fix(docker): when docker is not present do not try and use docker
  src/AM.Condo/Targets/Publish/Docker.targets
Labels: review

#209 fix: use docker-required rather than docker-enabled
  src/AM.Condo/Targets/Publish/Docker.targets
Labels: review

#210 feat: add a fork branch strategy for versioning
  src/AM.Condo/Targets/Version/GitForkFlow.targets
Labels: enhancement, review

#211 feat(node): expose build quality to scripts
  src/AM.Condo/Targets/Compile/Node.targets
  src/AM.Condo/Targets/Test/Node.targets
Labels: enhancement, review
